# Generated by Django 4.2.9 on 2024-11-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_card_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_passcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
